### ISSUE TITLE
Problema con Stow

### ISSUE THREAD

**Issue by ElModdy** [ClonedOne/c1-dotfiles#5]
Ciao,
ci sarebbe un modo per linkare tutti i file con un solo comando stow o devo fare
`stow <nome_del pacchetto>` per ogni pacchetto?
Grazie in anticipo e perdonate la mia ignoranza.

**Comment by ClonedOne** [comment]
Dovresti poter usare `stow *`, però il motivo per cui uso `stow`invece di altri strumenti come `yadm` (che ho usato per un po') è per avere più controllo sui dotfiles che metto su ogni macchina. Ad esempio su un server non mi interessa particolarmente la configurazione di Zathura.
